-- MySQL Script generated by MySQL Workbench
-- 10/22/16 01:11:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tpjava
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tpjava
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tpjava` DEFAULT CHARACTER SET utf8 ;
USE `tpjava` ;

-- -----------------------------------------------------
-- Table `tpjava`.`personajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpjava`.`personajes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `vida` INT(11) NULL DEFAULT NULL,
  `energia` INT(11) NULL DEFAULT NULL,
  `defensa` INT(11) NULL DEFAULT NULL,
  `evasion` INT(11) NULL DEFAULT NULL,
  `puntosDisponibles` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
